New watcher using `size` in macOS and Linux to analyze static memory usage before running.
Project-LemonLime/Project_LemonLime pull request #211
Opened 2023-06-10 20:02 UTC by tofucurd

在我的机子上经过验证，#185 #169 #142中macOS与Linux解决，lemon MLE判定已加入静态分析。
在两个watcher源码内加入使用`size`命令的片段，并在``fork()``之前就判定静态内存，实测可以防止以上issue的问题出现。
我的机子：
- macOS 13.1, Apple M1 Pro, 16 GB
- (VMware虚拟机)RHEL 9.1 Aarch64, 8 GB

2023-06-11 03:01 UTC, tofucurd commented
Windows没有环境实现。

2023-06-19 14:57 UTC, alphagocc commented on unix/watcher_macos.cpp
> +            size_t size__TEXT, size__DATA;
怎么变成双下划线了（

2023-06-19 14:57 UTC, alphagocc commented on unix/watcher_linux.cpp
> +    snprintf(command, sizeof(command), "size %s", executableName);
没处理长度超过256的情况来着。

2023-07-28 01:54 UTC, tofucurd commented on unix/watcher_macos.cpp
> +            size_t size__TEXT, size__DATA;
因为``size``输出就是``__TEXT`` ``__DATA``, 是可执行文件的文件头标识。

2023-07-28 03:03 UTC, Dust1404 requested changes

2023-07-28 03:03 UTC, Dust1404 commented on unix/watcher_linux.cpp
> +	char command[sizeof(executableName) + 128];
这里 `sizeof(executableName)` 是 8，是指针的大小，不是 `executableName` 的长度。或许可以使用 `PATH_MAX`，是系统最长的路径长度。

2023-07-28 03:05 UTC, tofucurd commented on unix/watcher_linux.cpp
> +    snprintf(command, sizeof(command), "size %s", executableName);
改成了``sizeof(executableName) + 128``, macos下最长为1024, linux下最长为4096
linux:
```cpp
#define PATH_MAX 4096
```
macos:
```cpp
#define MAX_INPUT                1024   /* max bytes in terminal input */
```

2023-07-28 03:07 UTC, tofucurd commented on unix/watcher_linux.cpp
> +	char command[sizeof(executableName) + 128];
改成了系统的max_path

2023-07-28 03:08 UTC, Dust1404 reviewed
hard code 是不建议的做法。另外注意一下缩进的统一。

2023-07-28 03:16 UTC, tofucurd commented
fix with using ``PATH_MAX`` in ``limits.h``

2023-07-28 03:42 UTC, Dust1404 reviewed
总体来说很有启发性也是可行的检查方法。

但是直接调用 command line tools，然后 parse 输出结果有很多问题。比如不同系统版本不同的 `size` 命令输出格式是否统一？未来是否会更改？同时 parse 过程也有一些很 tricky 的点，并不能保证对所有场景都一直有效。

直接去解析 elf 文件自己统计可能是更好的做法。

2023-07-28 03:42 UTC, Dust1404 commented on unix/watcher_linux.cpp
> +		if (buffer[3] >= '0' && buffer[3] <= '9') {
`[256]` 是否足够？`buffer[3]` 是否适合所有情况？

2023-07-28 07:11 UTC, tofucurd commented on unix/watcher_linux.cpp
> +		if (buffer[3] >= '0' && buffer[3] <= '9') {
256是够的

2023-07-28 07:16 UTC, tofucurd commented on unix/watcher_linux.cpp
> +		if (buffer[3] >= '0' && buffer[3] <= '9') {
其实主要的难点是跨平台的解析，以及第三方库的安装配置

2023-07-28 07:18 UTC, tofucurd commented on unix/watcher_linux.cpp
> +		if (buffer[3] >= '0' && buffer[3] <= '9') {
其实主要的难点是跨平台的解析，以及第三方库的安装配置

2023-08-06 15:52 UTC, closed without merging